### ISSUE TITLE
Some general questions

### ISSUE THREAD

**Issue by YukinoAi** [UserUnknownFactor/filetranslate#2]
I am so incredibly interested in everything you have done, but I have more just a few questions.

1) Why do you support pip installable directories if your programs are not on pypi? This makes using your program layouts incredibly confusing, especially because they cannot be used seperately and/or are [poorly documented](//github.com/UserUnknownFactor/psbtool_py). It makes any one program like [psbtool_py](https://github.com/UserUnknownFactor/psbtool_py) frustratingly difficult to use and install, especially since there are no instructions or binaries and just downloading and running them does not work at all due to lack of loose coupling.

- Download does not work without binaries.
- Download + run as `python script.py` does not work due to needing to be installed due to how the import statements are laid out.
- Download + install + run still does not work due to not supporting loose coupling.
- Download + install + `pip install requirements.txt` + run still does not work due to not supporting loose coupling for psbtool/wolf.

At this point, I just gave up. How many hoops do you think people should have to jump through to use your software? There is not any requirements.txt during install for psbtool_py and even when it is provided for wolf, it does not work since stuff is required that is not in the requirements.txt file. This level of disfunction is entering 'needs to be forked to fix it' territory.

2) Would you accept pull requests to update the documentation, add installation scripts (.bat/.sh) and/or contribute binaries? Which of those are fine and which are not?

3) Why do you not support [loose coupling](//en.wikipedia.org/wiki/Loose_coupling) for your programs? Like psbtool_py requires some random functions from [here](//github.com/UserUnknownFactor/filetranslate/blob/master/filetranslate/service_fn.py). That makes no sense! If the programs are seperate, then treat them seperately. If you believe one program is only valid to be used within in the context of another program, then it should be a module/subfolder in that larger program. Are they seperate or not? The folder structure does not imply they are tightly coupled but loose coupling is not supported either. What?

4) Would you accept pull requests that copy/paste your code to enable loose coupling? How much spaghetti is too much spaghetti? I have no upper limits at all, so please clarify if you have limits on copypasta.

5) What is the point of adding the __name__ == __main__ syntax to nearly every library when those libraries are not possible to execute due to not being standlone? No one can download them and just run them as normal scripts since the imports are non-sensical. It would be one thing if there were conditional `try` + `expect` import blocks to figure out if the files were being run as libraries or as standalone but... are you expecting people to `pip install .` and then `python C:\programs\python\libs\site-packages\psbtool_py\psbtool_py\tjs_tool.py` Are you really supporting that or am I missing something? Probably the latter. That syntax could work to make binaries with pyinstaller once everything *somehow* gets installed, but there are no binaries either! Just doing `pip install .` and `python psbtool_py\psbtool_py\tjs_tool.py` does not work, and yes, I tested it. This extra complexity seems wasted since the import statements do not allow the programs to run standalone without tons of installation steps and littering people's machines with unnecessary installations. Are you expecting people to always run everything in venv? So do you not support global installs? Document that!

6) The naming schemes are not necessarily consistent either, so I have no idea how to fix the import statements to not require installing. Like wolftrans is `wolftrans_py/wolfrpg/*` but there is no wolfrpg.py file. There is no wolftrans.py file at all! Is this project named `wolftrans_py`, `wolfrpg`, or something else? `psbtool_py` becomes `psb_tool.py` so `import psbtool_py` cannot possibly work. `import psbtool_py.psbtool_py` does not work either. It has to be `import psbtool_py.psb_tool` What? Why should that work but not the other ones?

7) Fundamentally, since nothing is standalone and half the files use __name__ == __main__ at the bottom, even when they are definitely libraries `import mylibrary`, and the folder structure does not clarify what is meant to be standalone `python script.py` or what is meant to be imported, *and* there is no documentation on it, I have no idea how you intend for other people to use your software. So... how do you intend for people to use it? Does it just depend on the file, and it is up to people to fix the import statements every time they want to use it to get stuff to work?

For some perspective, [functional programming](https://en.wikipedia.org/wiki/Functional_programming) like [this](https://github.com/UserUnknownFactor/filetranslate/blob/61aa8db3d8fc46a8fa44d4a64480b70a0756b675/filetranslate/service_fn.py#L11) and regex drives me crazy because I am 100% readability focused.
4) Due to that, I am unable to contribute original code to your projects without uh... breaking everything, so I will not try, but would you consider documentation, binaries, and install scripts?

You are a much better programmer than I am, so feel free to be as condescending as you like or just ignore my questions.

8) Also: <del>The project name of `filetranslate` is misleading/a lie because `filetranslate` does not translate files. How would you describe the actual functionality of your program? A game strings extraction tool focused on converting to tab.csv files with OCR support?</del>

Edit: I found it! There is this [carefully hidden](//github.com/UserUnknownFactor/filetranslate/blob/61aa8db3d8fc46a8fa44d4a64480b70a0756b675/filetranslate/filetranslate.py#L2102) import statement that imports [googletrans](//pypi.org/project/googletrans). The [requirements.txt](//github.com/UserUnknownFactor/filetranslate/blob/master/requirements.txt) should have also been a giveaway however. I missed it at first since this was not documented anywhere, and there is no install procedure at all.

Edit2:  Here is an [example](//github.com/satan53x/SExtractor) of a sane folder structure. Despite the incredible complexity and some questionable inclusions, there was genuine thought put into how to lay out the folder structure to clarify how everything is meant to be used and how everything interacts with each other. And there are user friendly shell scripts on top of that. Is there a particular reason to strongly prefer your current folder structure?

**Comment by UserUnknownFactor** [comment]
@YukinoAi: Sorry for the late reply.

>1. Why do you support pip installable directories if your programs are not on pypi? 

Pip compatibility is for local installation and package management. I'm too lazy to upload it to the public repository.
Just run `pip install --user .` from the repo's root directory and you're good to go.


>There is not any requirements.txt during install for psbtool_py and even when it is provided for wolf, it does not work since stuff is required that is not in the requirements.txt file.

These are mostly tools for personal use, so I assume everything they depend on is already installed unless it's not my module.  
For example, `filetranslate` is used by most of my other format packages, so I consider it installed by default.
That's why psbtool_py doesn't have any requirements since it doesn't depend on anything else.


>2. Would you accept pull requests to update the documentation, add installation scripts (.bat/.sh) and/or contribute binaries?

I'm fine with pull requests **without** any binary data in them, as long as you keep in mind that they'll probably be processed super slowly since I rarely visit github.

>3. Why do you not support [loose coupling](//en.wikipedia.org/wiki/Loose_coupling) for your programs? Like psbtool_py requires some random functions from service_fn.py.

See the second answer to the first question. Loose coupling is only needed if you are using things that are importable _generic_ modules.


>4. Would you accept pull requests that copy/paste your code to enable loose coupling?

No, please don't decouple them if you want to do PRs. This is an ecosystem and not separate packages. I can add `reuirements.txt` to everything with single filetranslate line in them though or make the dependency optional; let me think about it for some time.


>5. What is the point of adding the **name** == **main** syntax to nearly every library when those libraries are not possible to execute due to not being standlone?

`__main__` is the module entry and is executed when the file is run directly with `python file.py` or just `file.py` if it's associated, contrary to importing. It's mostly for debugging since pip creates binaries based on function names.


>6. The naming schemes are not necessarily consistent either, so I have no idea how to fix the import statements to not require installing.

It _requires_ module installation. The global/user pip installation automatically finds entry points for each module and produces the corresponding tools.
I don't currently use any of those as importable modules. If you want that just drop filetranslate dependency and return arrays instead of .csv files on disk.


>7. Fundamentally, since nothing is standalone and half the files use **name** == **main** at the bottom, even when they are definitely libraries

See the previous answer, they are not libraries.

>but would you consider documentation, binaries, and install scripts?

There's no need to do this (well, except documentation), since the pip already does everything.  
Simply add `%appdata%\python\PythonXXX\Scripts\` to your `%PATH%` on Windows to make the tools globally available.  

As for the documentation please ask what you don't understand and I'll try to answer/add it.  


>8. Also: ~The project name of `filetranslate` is misleading/a lie because `filetranslate` does not translate files. How would you describe the actual functionality of your program? A game strings extraction tool focused on converting to tab.csv files with OCR support?~

It translates files either text or binary using regexp parsing. Since you have original file as input and translated file as output, independently of their type.

>Is there a particular reason to strongly prefer your current folder structure?

For the format parsers, the directory structure is a copy of their original source structures, since they are mostly ports.  
And for filetranslate, there are too few files for one.
